## Mini Project - Text Similarity

This project illustrates multiplication of vectors and the use of cosine similarity method for estimation the correlation between vectors.


#### Store some text in three files:

- two of the files, let's call them A and B, contain texts, created by the same author X

- the third text - C - is created by another author - Y.

#### Create a program to convert the texts into vectors, to compare the vectors in pairs::

- A and B

- A and C

- B and C

and to suggest the authors of each text based on the calculated similarity coefficients.. You can use the provided example for directions.

In [2]:
import pandas as pd
import math

In [3]:
# Written by one author - Kim Larsen
koeb_bananer = open('koeb_bananer.txt','r', encoding='utf-8').read().lower()
midt_om_natten = open('midt_om_natten.txt','r', encoding='utf-8').read().lower()

# Written by another author - Sanne Salomonsen
i_en_taxa = open('i_en_taxa.txt','r', encoding='utf-8').read().lower()

In [4]:
koeb_bananer = koeb_bananer.split(' ')
midt_om_natten = midt_om_natten.split(' ')
i_en_taxa = i_en_taxa.split(' ')

In [5]:
all = set(koeb_bananer).union(set(midt_om_natten)).union(set(i_en_taxa))

In [6]:
dict_koeb_bananer = dict.fromkeys(all, 0) 
dict_midt_om_natten = dict.fromkeys(all, 0) 
dict_i_en_taxa = dict.fromkeys(all, 0) 

for word in koeb_bananer:
    dict_koeb_bananer[word]+=1

for word in midt_om_natten:
    dict_midt_om_natten[word]+=1
    
for word in i_en_taxa:
    dict_i_en_taxa[word]+=1

In [7]:
df = pd.DataFrame([dict_koeb_bananer, dict_midt_om_natten, dict_i_en_taxa])

In [9]:
def cosine(vector1, vector2):
     # calculate nominator as a dot product
     intersect = set(vector1.keys()) & set(vector2.keys())
     numerator = sum([vector1[x] * vector2[x] for x in intersect])
    
     # calculate the denominator 
     sum1 = sum([vector1[x] ** 2 for x in list(vector1.keys())])
     sum2 = sum([vector2[x] ** 2 for x in list(vector2.keys())])
    
     denominator = math.sqrt(sum1) * math.sqrt(sum2)
     if not denominator:
         return 0.0
     else:
         return float(numerator)/denominator

In [10]:
cosine(df.loc[0], df.loc[1])

0.22277459534602004

In [11]:
cosine(df.loc[0], df.loc[2])

0.2041844726856066

In [12]:
cosine(df.loc[1], df.loc[2])

0.1918368833932776

In [13]:
def computeTF(dicto, doc):
    tfDict = {}
    corpus = len(doc) # number of all words
    for word, wcount in dicto.items():
        tfDict[word] = wcount/float(corpus) # calculete the proportion
    return(tfDict)

In [14]:
tf1 = computeTF(dict_koeb_bananer, koeb_bananer)
tf2 = computeTF(dict_midt_om_natten, midt_om_natten)
tf3 = computeTF(dict_i_en_taxa, i_en_taxa)

In [15]:
tf = pd.DataFrame([tf1, tf2, tf3])
tf

,"bananer,",tog,drengen,pæn,sidde,stuerne.,hos,bananer,håber,du,...,onkel,"mig,",lidt,vand.,havde,mig.,pojken,åh,bli'r,det
0,0.003268,0.000000,0.006536,0.009804,0.003268,0.000000,0.01634,0.03268,0.000000,0.009804,...,0.009804,0.000000,0.003268,0.000000,0.003268,0.029412,0.003268,0.009804,0.013072,0.029412
1,0.000000,0.004695,0.000000,0.000000,0.000000,0.004695,0.00000,0.00000,0.032864,0.000000,...,0.000000,0.004695,0.000000,0.004695,0.000000,0.000000,0.000000,0.037559,0.004695,0.009390
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,0.000000,...,0.000000,0.011696,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [17]:
def computeIDF(docList):
    idf = {}
    N = len(docList)
    
    idf = dict.fromkeys(docList[0].keys(), 0)
    for word, wcount in idf.items():
        idf[word] = math.log10(N/(float(wcount) + 1))
        
    return(idf)

In [18]:
idfs = computeIDF([dict_koeb_bananer, dict_midt_om_natten, dict_i_en_taxa])
idfs

{'bananer,': 0.47712125471966244,
 'tog': 0.47712125471966244,
 'drengen': 0.47712125471966244,
 'pæn': 0.47712125471966244,
 'sidde': 0.47712125471966244,
 'stuerne.': 0.47712125471966244,
 'hos': 0.47712125471966244,
 'bananer': 0.47712125471966244,
 'håber': 0.47712125471966244,
 'du': 0.47712125471966244,
 'sin': 0.47712125471966244,
 'kviksølv': 0.47712125471966244,
 'for': 0.47712125471966244,
 'tikker.': 0.47712125471966244,
 "det'": 0.47712125471966244,
 'tættere': 0.47712125471966244,
 'vinduerne.': 0.47712125471966244,
 "nærmer'": 0.47712125471966244,
 'bindegal.': 0.47712125471966244,
 'kaldte': 0.47712125471966244,
 'med.': 0.47712125471966244,
 'noget!': 0.47712125471966244,
 'der': 0.47712125471966244,
 'af': 0.47712125471966244,
 'får': 0.47712125471966244,
 'sgu': 0.47712125471966244,
 'kan': 0.47712125471966244,
 'lys': 0.47712125471966244,
 'næppe': 0.47712125471966244,
 'mig': 0.47712125471966244,
 'men': 0.47712125471966244,
 'natten.': 0.47712125471966244,
 'et': 0.47712125471966244,
 'igen.': 0.47712125471966244,
 'gennem': 0.47712125471966244,
 'dem.': 0.47712125471966244,
 'vagt': 0.47712125471966244,
 'ingen': 0.47712125471966244,
 'øjne': 0.47712125471966244,
 'tør': 0.47712125471966244,
 'spejlet.': 0.47712125471966244,
 'stå': 0.47712125471966244,
 'bananskib': 0.47712125471966244,
 'kom': 0.47712125471966244,
 'hjem,': 0.47712125471966244,
 'drive': 0.47712125471966244,
 'alle': 0.47712125471966244,
 'trillede': 0.47712125471966244,
 'frue': 0.47712125471966244,
 'ved': 0.47712125471966244,
 'og': 0.47712125471966244,
 'nok': 0.47712125471966244,
 'som': 0.47712125471966244,
 'gammel': 0.47712125471966244,
 'pulsen': 0.47712125471966244,
 'når': 0.47712125471966244,
 'numsen': 0.47712125471966244,
 'ud,': 0.47712125471966244,
 'gjorde': 0.47712125471966244,
 'stiger.': 0.47712125471966244,
 'blå.': 0.47712125471966244,
 'to.': 0.47712125471966244,
 'før': 0.47712125471966244,
 'noget': 0.47712125471966244,
 'på,': 0.47712125471966244,
 'dine': 0.47712125471966244,
 'i': 0.47712125471966244,
 "ku'": 0.47712125471966244,
 'forstummer.': 0.47712125471966244,
 'tit': 0.47712125471966244,
 'de': 0.47712125471966244,
 'vel': 0.47712125471966244,
 'byen': 0.47712125471966244,
 'ligesom': 0.47712125471966244,
 'på\nmidt': 0.47712125471966244,
 'midt': 0.47712125471966244,
 'skete': 0.47712125471966244,
 'uret': 0.47712125471966244,
 'bare': 0.47712125471966244,
 'lyset': 0.47712125471966244,
 'syg': 0.47712125471966244,
 'mig!': 0.47712125471966244,
 'her': 0.47712125471966244,
 'lille': 0.47712125471966244,
 'på': 0.47712125471966244,
 'bananer.': 0.47712125471966244,
 'da': 0.47712125471966244,
 'nikke': 0.47712125471966244,
 'blik': 0.47712125471966244,
 'nærmeste': 0.47712125471966244,
 'skal': 0.47712125471966244,
 'nej': 0.47712125471966244,
 'nej.': 0.47712125471966244,
 'morgen': 0.47712125471966244,
 'hvor': 0.47712125471966244,
 'ud': 0.47712125471966244,
 'frue,': 0.47712125471966244,
 'lære': 0.47712125471966244,
 'cirka': 0.47712125471966244,
 'kvaj': 0.47712125471966244,
 'ja': 0.47712125471966244,
 'mit': 0.47712125471966244,
 'summer.': 0.47712125471966244,
 'sagde': 0.47712125471966244,
 'vejen': 0.47712125471966244,
 'står': 0.47712125471966244,
 'min': 0.47712125471966244,
 'fy': 0.47712125471966244,
 'taxa': 0.47712125471966244,
 'dig': 0.47712125471966244,
 'strisserne.': 0.47712125471966244,
 'hjørne.': 0.47712125471966244,
 'tænke': 0.47712125471966244,
 'gå': 0.47712125471966244,
 'siger': 0.47712125471966244,
 'frue.': 0.47712125471966244,
 'jeg': 0.47712125471966244,
 'fyr': 0.47712125471966244,
 'tit,': 0.47712125471966244,
 'skyld,': 0.47712125471966244,
 'drejer.': 0.47712125471966244,
 'endnu.': 0.47712125471966244,
 'ramte': 0.47712125471966244,
 'steder.': 0.47712125471966244,
 'skidt': 0.47712125471966244,
 'tøjet': 0.47712125471966244,
 'vil': 0.47712125471966244,
 'strisserne': 0.47712125471966244,
 'besøg.': 0.47712125471966244,
 'tårerne': 0.47712125471966244,
 'strøget': 0.47712125471966244,
 'han': 0.47712125471966244,
 'værelse': 0.47712125471966244,
 'mørket': 0.47712125471966244,
 "ka'": 0.47712125471966244,
 'gik': 0.47712125471966244,
 'mañana.': 0.47712125471966244,
 'ro.': 0.47712125471966244,
 'råbte:': 0.47712125471966244,
 'er': 0.47712125471966244,
 'lærte': 0.47712125471966244,
 'taxa.': 0.47712125471966244,
 'sal.': 0.47712125471966244,
 'nu': 0.47712125471966244,
 'læber.': 0.47712125471966244,
 'sådan': 0.47712125471966244,
 'spacey': 0.47712125471966244,
 "lukked'": 0.47712125471966244,
 'femte': 0.47712125471966244,
 'sit': 0.47712125471966244,
 'kassen': 0.47712125471966244,
 'om': 0.47712125471966244,
 'os': 0.47712125471966244,
 'vi': 0.47712125471966244,
 'spurgte,': 0.47712125471966244,
 'måtte': 0.47712125471966244,
 'lave': 0.47712125471966244,
 'stod': 0.47712125471966244,
 'ende': 0.47712125471966244,
 'gaden': 0.47712125471966244,
 'vores': 0.47712125471966244,
 'blinker.': 0.47712125471966244,
 'tre\nmidt': 0.47712125471966244,
 'chaufføren': 0.47712125471966244,
 'ske.': 0.47712125471966244,
 'tutti-frutti': 0.47712125471966244,
 'baby': 0.47712125471966244,
 'vidt,': 0.47712125471966244,
 'gas': 0.47712125471966244,
 'til': 0.47712125471966244,
 'kylede': 0.47712125471966244,
 'ikke': 0.47712125471966244,
 'kun': 0.47712125471966244,
 'skolen': 0.47712125471966244,
 'med': 0.47712125471966244,
 'sidst': 0.47712125471966244,
 'fra': 0.47712125471966244,
 'salig': 0.47712125471966244,
 'daddy': 0.47712125471966244,
 'klokken': 0.47712125471966244,
 'køb': 0.47712125471966244,
 'meget': 0.47712125471966244,
 'kære': 0.47712125471966244,
 'stille': 0.47712125471966244,
 'snydt': 0.47712125471966244,
 'hænder': 0.47712125471966244,
 'alt': 0.47712125471966244,
 'stage': 0.47712125471966244,
 'andet': 0.47712125471966244,
 'øjne,': 0.47712125471966244,
 'kommer': 0.47712125471966244,
 'ja.': 0.47712125471966244,
 'tro': 0.47712125471966244,
 'det.': 0.47712125471966244,
 'blev': 0.47712125471966244,
 'var': 0.47712125471966244,
 'råber:': 0.47712125471966244,
 'en': 0.47712125471966244,
 'den': 0.47712125471966244,
 'mand.': 0.47712125471966244,
 'så': 0.47712125471966244,
 'se': 0.47712125471966244,
 'ventede': 0.47712125471966244,
 'natten': 0.47712125471966244,
 'næste': 0.47712125471966244,
 'glæder': 0.47712125471966244,
 'smiler.': 0.47712125471966244,
 "bli'": 0.47712125471966244,
 'onkel': 0.47712125471966244,
 'mig,': 0.47712125471966244,
 'lidt': 0.47712125471966244,
 'vand.': 0.47712125471966244,
 'havde': 0.47712125471966244,
 'mig.': 0.47712125471966244,
 'pojken': 0.47712125471966244,
 'åh': 0.47712125471966244,
 "bli'r": 0.47712125471966244,
 'det': 0.47712125471966244}

In [19]:
def computeTFIDF(tf, idfs):
    tfidf = {}
    for word, wcount in tf.items():
        tfidf[word] = wcount*idfs[word]
    return(tfidf)

In [20]:
idf1 = computeTFIDF(tf1, idfs)
idf2 = computeTFIDF(tf2, idfs)
idf3 = computeTFIDF(tf3, idfs)

In [21]:
idf= pd.DataFrame([idf1, idf2, idf3])
idf

,"bananer,",tog,drengen,pæn,sidde,stuerne.,hos,bananer,håber,du,...,onkel,"mig,",lidt,vand.,havde,mig.,pojken,åh,bli'r,det
0,0.001559,0.00000,0.003118,0.004678,0.001559,0.00000,0.007796,0.015592,0.00000,0.004678,...,0.004678,0.00000,0.001559,0.00000,0.001559,0.014033,0.001559,0.004678,0.006237,0.014033
1,0.000000,0.00224,0.000000,0.000000,0.000000,0.00224,0.000000,0.000000,0.01568,0.000000,...,0.000000,0.00224,0.000000,0.00224,0.000000,0.000000,0.000000,0.017920,0.002240,0.004480
2,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,...,0.000000,0.00558,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000